#==============================================================================
# Simulation
#==============================================================================

SIMULATOR="ghdl"

#==============================================================================
# Executables
#==============================================================================

GHDL_BIN="ghdl"
QUESTA_BIN="vsim"
DOXYGEN_BIN="doxygen"
PYTHON_BIN="python3"
NODE_BIN="node"